// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Purchase.Api.Infrastructure.Persistence;

#nullable disable

namespace Purchase.Api.Migrations
{
    [DbContext(typeof(PurchaseDbContext))]
    partial class PurchaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Purchase.Api.Domain.Entities.MovementCab", b =>
                {
                    b.Property<int>("Id_MovimientoCab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_MovimientoCab"));

                    b.Property<DateTime>("Fec_registro")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_DocumentoOrigen")
                        .HasColumnType("int");

                    b.Property<int>("Id_TipoMovimiento")
                        .HasColumnType("int");

                    b.HasKey("Id_MovimientoCab");

                    b.ToTable("MovimientoCab", (string)null);
                });

            modelBuilder.Entity("Purchase.Api.Domain.Entities.MovementDet", b =>
                {
                    b.Property<int>("Id_MovimientoDet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_MovimientoDet"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_Producto")
                        .HasColumnType("int");

                    b.Property<int>("Id_movimientocab")
                        .HasColumnType("int");

                    b.HasKey("Id_MovimientoDet");

                    b.HasIndex("Id_movimientocab");

                    b.ToTable("MovimientoDet", (string)null);
                });

            modelBuilder.Entity("Purchase.Api.Domain.Entities.PurchaseCab", b =>
                {
                    b.Property<int>("Id_CompraCab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_CompraCab"));

                    b.Property<DateTime>("FecRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Igv")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id_CompraCab");

                    b.ToTable("CompraCab", (string)null);
                });

            modelBuilder.Entity("Purchase.Api.Domain.Entities.PurchaseDet", b =>
                {
                    b.Property<int>("Id_CompraDet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_CompraDet"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id_CompraCab")
                        .HasColumnType("int");

                    b.Property<int>("Id_producto")
                        .HasColumnType("int");

                    b.Property<decimal>("Igv")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sub_Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_CompraDet");

                    b.HasIndex("Id_CompraCab");

                    b.ToTable("CompraDet", (string)null);
                });

            modelBuilder.Entity("Purchase.Api.Domain.Entities.MovementDet", b =>
                {
                    b.HasOne("Purchase.Api.Domain.Entities.MovementCab", "MovementCab")
                        .WithMany("Details")
                        .HasForeignKey("Id_movimientocab")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovementCab");
                });

            modelBuilder.Entity("Purchase.Api.Domain.Entities.PurchaseDet", b =>
                {
                    b.HasOne("Purchase.Api.Domain.Entities.PurchaseCab", "PurchaseCab")
                        .WithMany("Details")
                        .HasForeignKey("Id_CompraCab")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseCab");
                });

            modelBuilder.Entity("Purchase.Api.Domain.Entities.MovementCab", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Purchase.Api.Domain.Entities.PurchaseCab", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
